export class AppError extends Error {
  constructor(
    public readonly statusCode: number,
    public readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = "AppError";
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export const ErrorCode = {
  // 400
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_LOGIN_REQUEST: "INVALID_LOGIN_REQUEST",
  INVALID_REGISTRATION_DATA: "INVALID_REGISTRATION_DATA",
  INVALID_PROFILE_UPDATE: "INVALID_PROFILE_UPDATE",
  INVALID_PASSWORD_UPDATE: "INVALID_PASSWORD_UPDATE",
  INVALID_EMAIL_VERIFICATION_DATA: "INVALID_EMAIL_VERIFICATION_DATA",
  INVALID_EMAIL_VERIFICATION_CODE: "INVALID_EMAIL_VERIFICATION_CODE",
  EMAIL_VERIFICATION_EXPIRED: "EMAIL_VERIFICATION_EXPIRED",
  EMAIL_VERIFICATION_ALREADY_SENT: "EMAIL_VERIFICATION_ALREADY_SENT",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  NO_PASSWORD_SET: "NO_PASSWORD_SET",
  PASSWORD_ALREADY_SET: "PASSWORD_ALREADY_SET",
  EMPTY_PROFILE_UPDATE: "EMPTY_PROFILE_UPDATE",
  MISSING_USER_FILTER: "MISSING_USER_FILTER",
  TWO_FACTOR_SETUP_REQUIRED: "TWO_FACTOR_SETUP_REQUIRED",
  TWO_FACTOR_NOT_ENABLED: "TWO_FACTOR_NOT_ENABLED",
  INVALID_NOTIFICATION_DATA: "INVALID_NOTIFICATION_DATA",
  EMPTY_NOTIFICATION_UPDATE: "EMPTY_NOTIFICATION_UPDATE",
  // 401
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  INVALID_TWO_FACTOR_CODE: "INVALID_TWO_FACTOR_CODE",
  INVALID_TWO_FACTOR_TEMP_TOKEN: "INVALID_TWO_FACTOR_TEMP_TOKEN",
  INVALID_RESET_PASSWORD_TOKEN: "INVALID_RESET_PASSWORD_TOKEN",
  RESET_PASSWORD_TOKEN_EXPIRED: "RESET_PASSWORD_TOKEN_EXPIRED",
  // 404
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  // 409
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  TWO_FACTOR_ALREADY_ENABLED: "TWO_FACTOR_ALREADY_ENABLED",
  // 403
  USER_DISABLED: "USER_DISABLED",
  // provider / integration
  GOOGLE_ACCOUNT_EMAIL_MISSING: "GOOGLE_ACCOUNT_EMAIL_MISSING",
  DATABASE_NOT_INITIALIZED: "DATABASE_NOT_INITIALIZED",
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  EMAIL_DELIVERY_FAILED: "EMAIL_DELIVERY_FAILED",
  // album
  INVALID_ALBUM_DATA: "INVALID_ALBUM_DATA",
  INVALID_STICKER_CODE: "INVALID_STICKER_CODE",
  INVALID_ALBUM_ROLE_DATA: "INVALID_ALBUM_ROLE_DATA",
  INVALID_INVITATION_DATA: "INVALID_INVITATION_DATA",
  MEMBER_ALREADY_EXISTS: "MEMBER_ALREADY_EXISTS",
  INVITATION_ALREADY_PENDING: "INVITATION_ALREADY_PENDING",
  INVITATION_NOT_PENDING: "INVITATION_NOT_PENDING",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  ALBUM_ROLE_IN_USE: "ALBUM_ROLE_IN_USE",
  // 500
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;
